//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurdurAdliyeProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rehber
    {
        public int Id { get; set; }
        public string DahiliNo { get; set; }
        public Nullable<int> Personel { get; set; }
    
        public virtual Personeller Personeller { get; set; }
    }
}
